### ISSUE TITLE
make newdb error

### ISSUE THREAD

**Issue by kahfiAG** [dogoncouch/ldsi#12]
## New App Idea
was installing in ubuntu 16.04LTS had everything configured with virtual environment python 3
`(env) root@syslogserver-VirtualBox:/opt/LogESP# python --version
Python 3.5.2`

## Feature Idea
the error 

> (env) root@syslogserver-VirtualBox:/opt/LogESP# make newdb
--- Loading initial migrations...
python manage.py migrate
Traceback (most recent call last):
  File "/opt/LogESP/env/lib/python3.5/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/LogESP/env/lib/python3.5/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/LogESP/env/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/LogESP/env/lib/python3.5/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/opt/LogESP/env/lib/python3.5/site-packages/MySQLdb/connections.py", line 164, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1698, "Access denied for user 'logespd'@'localhost'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/LogESP/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/LogESP/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/LogESP/env/lib/python3.5/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/LogESP/env/lib/python3.5/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/opt/LogESP/env/lib/python3.5/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/opt/LogESP/env/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 64, in _run_checks
    issues = run_checks(tags=[Tags.database])
  File "/opt/LogESP/env/lib/python3.5/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/opt/LogESP/env/lib/python3.5/site-packages/django/core/checks/database.py", line 10, in check_database_backends
    issues.extend(conn.validation.check(**kwargs))
  File "/opt/LogESP/env/lib/python3.5/site-packages/django/db/backends/mysql/validation.py", line 9, in check
    issues.extend(self._check_sql_mode(**kwargs))
  File "/opt/LogESP/env/lib/python3.5/site-packages/django/db/backends/mysql/validation.py", line 13, in _check_sql_mode
    with self.connection.cursor() as cursor:
  File "/opt/LogESP/env/lib/python3.5/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/opt/LogESP/env/lib/python3.5/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/opt/LogESP/env/lib/python3.5/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/LogESP/env/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/LogESP/env/lib/python3.5/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/LogESP/env/lib/python3.5/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/LogESP/env/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/LogESP/env/lib/python3.5/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/opt/LogESP/env/lib/python3.5/site-packages/MySQLdb/connections.py", line 164, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1698, "Access denied for user 'logespd'@'localhost'")
Makefile:90: recipe for target 'newdb-setup' failed
make: *** [newdb-setup] Error 1

### Overview
many thanks would love to hear your response : )
### Specifications
- LogESP version (in `LogESP/__init__.py`): 
- Python version: 
- Django version: 
- Operating system: 
- Operating system version: 
- Deployment info
  - SQL server name/version: 
  - SQL client library name/version: 
  - WSGI name/version: 
  - Web server name/version: 
- Log file type: 
- Other info that might be useful:

**Comment by kahfiAG** [comment]
db password was mistaken
